services:
  chat-frontend:
    build: .
    network_mode: "host" 
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - OLLAMA_HOST=localhost
    volumes:
      - ./chat_history.db:/app/chat_history.db
      - ./exports:/app/exports
    restart: unless-stopped  # 添加自动重启